server:
  port: 8082

spring:
  data:
    mongodb:
      uri: mongodb+srv://${DB_USER:admin}:${DB_PASSWORD}@webfluxcluster.sd1bi.mongodb.net/${DB_NAME:webflux-course}?retryWrites=true&w=majority&appName=WebfluxCluster
      auto-index-creation: true
    application:
    name: webflux-course